spring:
  datasource:
    url: jdbc:mysql://localhost:3306/review
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
